server:
  port: 8080

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      transactionCircuitBreaker:
        baseConfig: default
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 50
      notificationCircuitBreaker:
        baseConfig: default
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 50
